name: NodeJS with Webpack

on:
  push:
    branches: [ "release/**" ]
  pull_request:
    branches: [ "release/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack

    - name: Zip Folder
      uses: montudor/action-zip@v1.0.0
      with:
        args: zip -qq -r ${{ github.event.repository.name }}.zip manifest.json dist
    
    - name: Upload Release File
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ github.event.repository.name }}-${{ github.ref }}.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
